on: # yamllint disable-line rule:truthy
  pull_request: ~
  push:
    branches:
      - "main"
      - "[0-9].*"

name: "BC Check"

jobs:
  roave-bc-check:
    name: "Roave BC Check"
    runs-on: "ubuntu-latest"

    steps:
      - name: "Checkout code"
        uses: "actions/checkout@v3"

      - name: "Roave BC Check"
        uses: "addnab/docker-run-action@v3"
        with:
          image: "nyholm/roave-bc-check-ga"
          options: "-v ${{ github.workspace }}:/app -u $UID:$UID"
          run: "/entrypoint.sh"
